#!/bin/bash

#cd /home/pjjp/Desktop/c++_temp_file
cd /home/pjjp/Desktop

#echo Nazwa programu:
#read nazwa_p
#r=".cpp"
#concatenation="$nazwa_p$r"
#g++ $concatenation -o $nazwa_p

nazwa="kacper"
r=".cpp"
concatenation="$nazwa$r"
g++ -std=c++0x $concatenation -o $nazwa
echo $concatenation

echo _______________________________
echo

#./$nazwa_p
./$nazwa
